### ISSUE TITLE
lack of LICENSE/AUTHORS is a violation of the pygments license

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [trevorturk/pygments#1]
i would like to suggest to either add those files as well,
or take pygments in as dependency

since just leaving them out while including the source is actually a violation

**Comment by trevorturk** [comment]
I'm not sure what you mean. A pull request would be welcome. I'm not trying to do anything shady -- I just don't know the rules.

**Comment by margauxmcmillin** [comment]
@trevorturk:

Looks like you just need to add the LICENSE file:
https://bitbucket.org/birkenfeld/pygments-main/src/4e66a4c4b3ed/LICENSE

and the AUTHORS file:
https://bitbucket.org/birkenfeld/pygments-main/src/4e66a4c4b3ed/AUTHORS

**Comment by RonnyPfannschmidt** [comment]
my personal suggestion would be to change pygments to a dependency (frees you from licensing voodoo and makes upgrades easier), but i have no idea how to deploy that on appengine

**Comment by trevorturk** [comment]
I added those two files. I think that should be OK but please let me know if not.
